module_VI/backend/lab6/cidei/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cidei.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'app.views.index', name="index"),
    url(r'^categories/$', 'app.views.categories', name="categories"),
    url(r'^categories/add/$', 'app.views.add_category', name="add-category"),
    url(r'^categories/(?P<slug>[\w-]+)/$', 'app.views.category', name="category"),
    url(r'^categories/(?P<slug>[\w-]+)/edit/$', 'app.views.edit_category', name="edit-category"),
    url(r'^items/$', 'app.views.items', name="items"),
    url(r'^items/add/$', 'app.views.add_item', name="add-item"),
    url(r'^items/(?P<item_id>\d+)/$', 'app.views.item', name="item"),
    url(r'^items/ajax/$', 'app.views.ajax_items', name="ajax_items"),
)

module_VI/backend/lab6/app/models.py
from django.db import models

L_TYPES = (
    ('t', 'Para resolver'),
	('l', 'Para revisar'),
	('p', 'No resuelto'),
)

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __unicode__(self):
		return "%s - %s" % (self.name, self.slug)

class Item(models.Model):
    listing = models.CharField(max_length=1, choices=L_TYPES, default='T')
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category)
    department = models.CharField(max_length=255)
    description = models.TextField()
    posted_on = models.DateTimeField(auto_now_add=True)
    update_item = models.DateTimeField()

    def __unicode__(self):
		return "%s - %s - %s - %s - %s" % (self.name, self.category, self.department, self.description, self.update_item)

class Picture(models.Model):
    item = models.ForeignKey(Item)
    url = models.CharField(max_length=255)

module_VI/backend/lab6/app/forms.py
from django import forms

from app.models import L_TYPES, Category, Item

class CategoryForm(forms.Form):
	name = forms.CharField(max_length=255)
	slug = forms.SlugField(max_length=255)
	"""
	class Meta:
		model = Category
	"""
class ItemForm(forms.Form):
	listing = forms.ChoiceField(choices=L_TYPES, initial='t')
	name = forms.CharField(max_length=255)
	category = forms.ModelChoiceField(Category.objects.all())
	department = forms.CharField(max_length=255)
	description = forms.CharField(widget=forms.Textarea)
	update_item = forms.DateTimeField()

module_VI/backend/lab6/app/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render_to_response, get_object_or_404, HttpResponseRedirect
from django.template import Context, RequestContext
from app.models import Item, Category, Picture
from app.forms import CategoryForm, ItemForm
# Modulo serializador de QuerySets para Django
from django.http import HttpResponse
from django.core.serializers import serialize
import json

def index(request):
	context = Context({'title' : 'Hola CIDEI'})
	return render_to_response('index.html', context)

def categories(request):
	categories = Category.objects.all()
	context = Context({'title' : 'Hola CIDEI', 'categories' : categories})
	return render_to_response('categories.html', context)

def category(request, slug):
	category = get_object_or_404(Category, slug=slug)
	context = Context({'title' : 'Detalle categoria', 'category' : category})
	return render_to_response('category-details.html', context)

def add_category(request):
	if request.method == "POST":
		form = CategoryForm(request.POST)
		if form.is_valid():
			# Crear un nuevo category
			category = Category.objects.create(
				name = form.cleaned_data['name'],
				slug = form.cleaned_data['slug'],
			)
			# Siempre que cree el dato correctamente redireccionar
			return HttpResponseRedirect('/categories/%s/' % category.slug)
	else:
		form = CategoryForm()

	context = Context({'title':'Creación de categorias', 'form': form})
	return render_to_response('add-category.html', context, context_instance=RequestContext(request))

def edit_category(request, slug):
	category = get_object_or_404(Category, slug=slug)
	if request.method == "POST":
		form = CategoryForm(request.POST)
		if form.is_valid():
			category.name = form.cleaned_data['name']
			category.slug = form.cleaned_data['slug'] 
			category.save()

			return HttpResponseRedirect('/categories/%s/' % category.slug)
	else:
		category_data = {
			'name' : category.name,
			'slug' : category.slug
		}

		form = CategoryForm(initial=category_data)

	context = Context({'title' : 'Editar la Categoria', 'form' : form, 'info_button' : 'Actualizar Categoria'})
	return render_to_response('add-category.html', context, context_instance=RequestContext(request))

def items(request):
	items = Item.objects.all()
	context = Context({'title' : 'Hola CIDEI', 'items' : items})
	return render_to_response('items.html', context)

def item(request, item_id):
	item = get_object_or_404(Item, id=item_id)
	pictures = Picture.objects.filter(item=item)
	count_pictures = pictures.count()
	context = Context({
		'title' : 'Hola CIDEI',
		'item' : item,
		'pictures':pictures,
		'count_pictures' : count_pictures
	})
	return render_to_response('item-details.html', context)

def add_item(request):
	if request.method == "POST":
		form = ItemForm(request.POST)
		if form.is_valid():
			# Crear un nuevo item
			item = Item.objects.create(
				listing = form.cleaned_data['listing'],
				name = form.cleaned_data['name'],
				category=form.cleaned_data['category'],
				department=form.cleaned_data['department'],
				description = form.cleaned_data['description'],
				update_item = form.cleaned_data['update_item'],
			)
			# Siempre que cree el dato correctamente redireccionar
			return HttpResponseRedirect('/items/%s/' % item.id)
	else:
		form = ItemForm()

	context = Context({'title' : 'Adicionar item', 'form' : form})
	return render_to_response('add-item.html', context, context_instance=RequestContext(request))

def items(request):
	items = Item.objects.all()
	context = Context({'title' : 'Hola CIDEI', 'items' : items})
	return render_to_response('items.html', context)

def item(request, item_id):
	item = get_object_or_404(Item, id=item_id)
	pictures = Picture.objects.filter(item=item)
	count_pictures = pictures.count()
	context = Context({
		'title' : 'Hola CIDEI',
		'item' : item,
		'pictures':pictures,
		'count_pictures' : count_pictures
	})
	return render_to_response('item-details.html', context)

def add_item(request):
	if request.method == "POST":
		form = ItemForm(request.POST)
		if form.is_valid():
			# Crear un nuevo item
			item = Item.objects.create(
				listing = form.cleaned_data['listing'],
				name = form.cleaned_data['name'],
				category=form.cleaned_data['category'],
				department=form.cleaned_data['department'],
				description = form.cleaned_data['description'],
				update_item = form.cleaned_data['update_item'],
			)
			# Siempre que cree el dato correctamente redireccionar
			return HttpResponseRedirect('/items/%s/' % item.id)
	else:
		form = ItemForm()

	context = Context({'title' : 'Adicionar item', 'form' : form})
	return render_to_response('add-item.html', context, context_instance=RequestContext(request))

def ajax_items(request):
	if request.is_ajax():
		items = Item.objects.all()
		print items
		items = serialize('json', items)
		print items
		items = json.dumps(items)
		print items

		return HttpResponse(items, content_type='application/json')
	else:
		return HttpResponse({'error' : 'Hubo un error'}, content_type='application/json')

module_VI/backend/lab6/templates/add-category.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<form action="." method="POST">
		{% csrf_token %}
			{{form.as_p }}
			{# Comentario en el template #}
			<input type="submit" value="{{ info_button }}" />
		</form>
	</body>
</html>

module_VI/backend/lab6/templates/add-item.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<form action="." method="POST">
		{% csrf_token %}
			{{form.as_p }}
			{# Comentario en el template #}
			<input type="submit" value="Adicionar Item" />
		</form>
	</body>
</html>

module_VI/backend/lab6/templates/categories.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<ul>
		{% for category in categories %}
			<li><a href="{% url 'category' category.slug %}">{{ category.name|capfirst }}</a></li>
		{% endfor %}
		</ul><br>
		<a href="{% url 'index' %}">Volver al inicio</a>
	</body>
</html>

module_VI/backend/lab6/templates/category-details.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<a href="{% url 'edit-category' category.slug %}">Editar Categoria</a>
		<ul>
			<li>Nombre: {{ category.name }}</li>
			<li>Categoria: {{ category.slug }}</li>
		</ul><br />
		<a href="{% url 'categories' %}">Regresar a la lista de Categorias</a>
		<a href="{% url 'index' %}">Volver al inicio</a>
	</body>
</html>

module_VI/backend/lab6/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>{{ title }}</title>
		<script src="{% static "js/jquery-1.11.1.min.js" %}"></script>
		<script src="{% static "js/jquery.cookie.js" %}"></script>
		<script src="{% static "js/lab6.js" %}"></script>
	</head>
	<body>
		<h1>{{ title }}</h1>
		{# <a href="/categories/">Categorias</a> #}
		<a href="{% url 'categories' %}">Categorias</a>
		{# <a href="/items/">Items</a><br> #}
		<a href="{% url 'items' %}">Items</a><br>
		<h1>Crear elementos</h1>
		{#<a href="{% url 'add-category' %}">Crear Categoria</a> #}
		<a href="{% url 'add-category' %}">Crear Categoria</a>
		{# <a href="/items/add/">Crear Categoria</a> #}
		<a href="{% url 'add-item' %}">Adicionar item</a>
	</body>
</html>

module_VI/backend/lab6/templates/item-details.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
		<script src="{% static "js/jquery-1.11.1.min.js" %}"></script>
		<script src="{% static "js/jquery.cookie.js" %}"></script>
		<script src="{% static "js/lab6.js" %}"></script>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<ul>
			<li>Nombre: {{ item.name }}</li>
			<li>Categoria: {{ item.category.name }}</li>
			<li>Listado: {{ item.get_listing_display }}</li>
			<li>Departamento: {{ item.department }}</li>
			<li>Creado: {{ item.posted_on|date }}</li>
		</ul>
		<h2>Descripción</h2>
		<p>{{ item.description|linebreaksbr }}</p>
		{% if count_pictures == 0 %}
			<h2>No tiene imagenes subidas</h2>
		{% else %}
			{% for picture in pictures %}
			<h2>Tiene {{ count_pictures }} Imagenes subidas</h2>
			<img src="{{ picture.url }}" alt="">
			{% endfor %}
		{% endif %}
		<br>
		<a href="{% url 'items' %}">Regresar a la lista de items</a>
		<a href="{% url 'index' %}">Volver al inicio</a>
		<br>
		<a href="#" id="getAllItems">Traer el resto de items a través de AJAX con Django</a>		
		<div id="resultAllItems"></div>
	</body>
</html>

module_VI/backend/lab6/templates/items.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		<h1>{{ title }}</h1>
		<ul>
		{% for item in items %}
			<li><a href="{% url 'item' item.id %}">{{ item.name|capfirst }}</a></li>
		{% endfor %}
		</ul><br>
		<a href="{% url 'index' %}">Volver al inicio</a>
	</body>
</html>